Merging in Defect Density and Issue Spoilage
AJM10565/SSLMetrics pull request #31
Opened 2020-04-06 23:20 UTC by MartinZugs

Give this a look and see if the code works for you. I did not do the fancy way of implementation like @NicholasSynovic has been (although it probably would be better!) but this is working and I believe error free and running using the DB in the volume. Give it a shot and let me know if this works!

2020-04-07 04:50 UTC, jonathanwarkentin requested changes
Commits, Issues, Defect Density all seem to be running fine.
After running all those, got this error on running Issue Spoilage:
`AttributeError: module 'Defect_Density_Issue_Spoilage' has no attribute 'main'`

2020-04-13 13:25 UTC, MartinZugs commented
That should have fixed the bug you were running into @jonathanwarkentin

2020-04-17 03:01 UTC, linmaliakal submitted a review, later dismissed
looks good

2020-04-17 03:04 UTC, jonathanwarkentin submitted a review, later dismissed

2020-04-17 05:02 UTC, merged